name: Build
on: push
permissions: write-all

jobs:
  build:
    runs-on: windows-latest  # 更改執行環境為 Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Install jq
        run: choco install jq -y  # 使用 Chocolatey 安裝 jq
        shell: pwsh  # 指定 PowerShell 執行環境

      - name: Get Name and Icon from JSON
        shell: pwsh
        run: |
          $name = Get-Content info.json | jq -r '.id'
          $icon = Get-Content info.json | jq -r '.icon'
          echo "NAME=$name" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ICON=$icon" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create ZIP Archive
        shell: pwsh
        run: Compress-Archive -Path info.json, $env:ICON, main.js -DestinationPath "$env:NAME.potext"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}.potext
          path: "*.potext"
          if-no-files-found: error

      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "*.potext"
